[package]
name = "day12"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
divan = "0.1.14"
assertables ="7.0.0"
[[bench]]
name = "criterion"
harness = false

[[bench]]
name = "divan"
harness = false
